// src/app/layout.jsx
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className="font-sans bg-white text-gray-900">
        <nav className="p-4 border-b border-gray-300 bg-gray-100">
          <div className="flex space-x-4">
            <Link href="/" className="text-blue-600 hover:underline">Home</Link>
            <Link href="/about-us" className="text-blue-600 hover:underline">About Us</Link>
            <Link href="/contact-us" className="text-blue-600 hover:underline">Contact Us</Link>
          </div>
        </nav>
        <main className="p-6">
          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
